/*
          __ _/| _/. _  ._/__ /
        _\/_// /_///_// / /_|/
                   _/
        copyright (c) sof digital 2021
        written by michael rinderle <michael@sofdigital.net>
*/

namespace Headtrip
{
    public static class Constants
    {
        public static readonly string SyncfusionLicense = "NTE0NzI2QDMxMzkyZTMzMmUzMEl2Y2VMZW43TWlkUTdYVWZaelpvb1pUaTYyVWxZZ0hmaXFtTGFEVzVoSVk9;NTE0NzI3QDMxMzkyZTMzMmUzMEQrWktxQXVmOXRTdXRMYWJsUDJMb05XajVZV1F1aUFMNDJ0WnVRYkVKclE9;NTE0NzI4QDMxMzkyZTMzMmUzMEJHT1QvL2NuOVQ2Y3IwUXZXYS94NnZBTXNOMGNISGdWRE0wYy9qMmZGa3c9;NTE0NzI5QDMxMzkyZTMzMmUzMFRlTTB2bDhrVnJidUlKY0d6cmZtNWVPKzdTNGI4N3JUUHJBM05sdDRPV3M9;NTE0NzMwQDMxMzkyZTMzMmUzMEJJV05LRnJSQUw4YzNkVHJmZUhLUWxHemI4SEgwVGVROXV0RDREa1AvWVU9;NTE0NzMxQDMxMzkyZTMzMmUzMERHMlpxK3ZCd3IvS1pSSEFDWmVVVmV0YlpHMHNaamUrOWE1YkRNTmtJQ0k9;NTE0NzMyQDMxMzkyZTMzMmUzMFAvMzlXQlJFZVpaTXFIQmdNWnBuU2hzYUUrcFk4TGxwRnFXdk1jNmh2NEU9;NTE0NzMzQDMxMzkyZTMzMmUzMEpxc1VydDA2b0Mxc1ZNOGNUSlM0QU1oMDZRSXlzWDJCempTbDBHZCtNd0k9;NTE0NzM0QDMxMzkyZTMzMmUzMFUvS3grMFExbXp4M1MyQ3AwZ2VVSW56cmhaOUZ4VjJRODJlbGxqTktBMlk9;NTE0NzM1QDMxMzkyZTMzMmUzMFd6V2o5UVJJL1BWT2s4eDkvZGRXekc5VDM5YW5RY20vdjE2cHg0Zis3d1U9;NTE0NzM2QDMxMzkyZTMzMmUzMFFzaGtiY2FuM2ZKOHkwdGYybkZYZHV5aUE5MUsyanN3cWt0MkN6ck1NRk09";
    }
}
